spring:
  application:
    name: LibraryManagement

  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 10
        one-indexed-parameters: false


#jwt config
jwt:
  secret: ${JWT_SECRET:dNrao7M7UiqcgkkxLK1B6eTWypjfxOx5ixAkZPTrH83R0bvGKjtfmZbjrGlJ9D7z}
  expiration: ${JWT_EXPIRATION:3600000}